/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chbs;

/**
 *
 * @author Simon
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNewConcert = new javax.swing.JPanel();
        lblAddNewConcert1 = new javax.swing.JLabel();
        lblNewConcertName = new javax.swing.JLabel();
        txtNewConcertName = new javax.swing.JTextField();
        lblNewConcertDate = new javax.swing.JLabel();
        lblNewConcertOrganiser = new javax.swing.JLabel();
        txtNewConcertDate = new javax.swing.JTextField();
        txtNewConcertOrganiser = new javax.swing.JTextField();
        lblNewConcertGold = new javax.swing.JLabel();
        lblNewConcertSilver = new javax.swing.JLabel();
        lblNewConcertBronze = new javax.swing.JLabel();
        txtNewConcertGold = new javax.swing.JTextField();
        txtNewConcertSilver = new javax.swing.JTextField();
        txtNewConcertBronze = new javax.swing.JTextField();
        btnAddNewConcert = new javax.swing.JButton();
        pnlExistingConcert = new javax.swing.JPanel();
        lblExistingConcert = new javax.swing.JLabel();
        lblExistingConcertName = new javax.swing.JLabel();
        lblExistingConcertDate = new javax.swing.JLabel();
        lblExistingConcertOrganiser = new javax.swing.JLabel();
        lblExistingConcertGold = new javax.swing.JLabel();
        lblExistingConcertSilver = new javax.swing.JLabel();
        lblExistingConcertBronze = new javax.swing.JLabel();
        dlblExistingConcertName = new javax.swing.JLabel();
        dlblExistingConcertDate = new javax.swing.JLabel();
        dlblExistingConcertOrganiser = new javax.swing.JLabel();
        dlblExistingConcertGold = new javax.swing.JLabel();
        dlblExistingConcertSilver = new javax.swing.JLabel();
        dlblExistingConcertBronze = new javax.swing.JLabel();
        btnEditExistingConcert = new javax.swing.JButton();
        btnDeleteExistingConcert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 730));

        lblAddNewConcert1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddNewConcert1.setText("Add a New Concert");

        lblNewConcertName.setText("Concert Name:");

        lblNewConcertDate.setText("Concert Date:");

        lblNewConcertOrganiser.setText("Organised By:");

        lblNewConcertGold.setText("Seat Price - Gold(£):");

        lblNewConcertSilver.setText("Seat Price - Silver(£):");

        lblNewConcertBronze.setText("Seat Price - Bronze(£):");

        txtNewConcertGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewConcertGoldActionPerformed(evt);
            }
        });

        btnAddNewConcert.setText("Add New Concert");

        javax.swing.GroupLayout pnlNewConcertLayout = new javax.swing.GroupLayout(pnlNewConcert);
        pnlNewConcert.setLayout(pnlNewConcertLayout);
        pnlNewConcertLayout.setHorizontalGroup(
            pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewConcertLayout.createSequentialGroup()
                .addComponent(lblAddNewConcert1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlNewConcertLayout.createSequentialGroup()
                .addGroup(pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewConcertLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNewConcertLayout.createSequentialGroup()
                                .addComponent(lblNewConcertOrganiser)
                                .addGap(29, 29, 29)
                                .addComponent(txtNewConcertOrganiser, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNewConcertBronze))
                            .addGroup(pnlNewConcertLayout.createSequentialGroup()
                                .addGroup(pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNewConcertName)
                                    .addComponent(lblNewConcertDate))
                                .addGroup(pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlNewConcertLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(txtNewConcertDate, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                    .addGroup(pnlNewConcertLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNewConcertName)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNewConcertGold)
                                    .addComponent(lblNewConcertSilver))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNewConcertSilver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(txtNewConcertGold, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewConcertBronze)))
                    .addGroup(pnlNewConcertLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnAddNewConcert)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlNewConcertLayout.setVerticalGroup(
            pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewConcertLayout.createSequentialGroup()
                .addComponent(lblAddNewConcert1)
                .addGap(18, 18, 18)
                .addGroup(pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewConcertName)
                    .addComponent(txtNewConcertName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewConcertGold)
                    .addComponent(txtNewConcertGold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewConcertDate)
                    .addComponent(txtNewConcertDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewConcertSilver)
                    .addComponent(txtNewConcertSilver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewConcertOrganiser)
                    .addComponent(txtNewConcertOrganiser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewConcertBronze)
                    .addComponent(txtNewConcertBronze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnAddNewConcert))
        );

        lblExistingConcert.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblExistingConcert.setText("Existing Concert Details");

        lblExistingConcertName.setText("Concert Name:");

        lblExistingConcertDate.setText("Concert Date:");

        lblExistingConcertOrganiser.setText("Organised By:");

        lblExistingConcertGold.setText("Seat Price - Gold(£):");

        lblExistingConcertSilver.setText("Seat Price - Silver(£):");

        lblExistingConcertBronze.setText("Seat Price - Bronze(£):");

        dlblExistingConcertName.setText("CLEAR");

        dlblExistingConcertDate.setText("CLEAR");

        dlblExistingConcertOrganiser.setText("CLEAR");

        dlblExistingConcertGold.setText("CLEAR");

        dlblExistingConcertSilver.setText("CLEAR");

        dlblExistingConcertBronze.setText("CLEAR");

        btnEditExistingConcert.setText("Edit Existing Concert");

        btnDeleteExistingConcert.setText("Delete Existing Concert");

        javax.swing.GroupLayout pnlExistingConcertLayout = new javax.swing.GroupLayout(pnlExistingConcert);
        pnlExistingConcert.setLayout(pnlExistingConcertLayout);
        pnlExistingConcertLayout.setHorizontalGroup(
            pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExistingConcertLayout.createSequentialGroup()
                .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExistingConcert)
                    .addGroup(pnlExistingConcertLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExistingConcertName)
                            .addComponent(lblExistingConcertDate)
                            .addComponent(lblExistingConcertOrganiser))
                        .addGap(21, 21, 21)
                        .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlExistingConcertLayout.createSequentialGroup()
                                .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlExistingConcertLayout.createSequentialGroup()
                                        .addComponent(dlblExistingConcertOrganiser)
                                        .addGap(147, 147, 147)
                                        .addComponent(lblExistingConcertBronze))
                                    .addGroup(pnlExistingConcertLayout.createSequentialGroup()
                                        .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dlblExistingConcertName)
                                            .addComponent(dlblExistingConcertDate))
                                        .addGap(147, 147, 147)
                                        .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblExistingConcertGold)
                                            .addComponent(lblExistingConcertSilver))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dlblExistingConcertGold)
                                    .addComponent(dlblExistingConcertSilver)
                                    .addComponent(dlblExistingConcertBronze)))
                            .addGroup(pnlExistingConcertLayout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(btnDeleteExistingConcert))))
                    .addGroup(pnlExistingConcertLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnEditExistingConcert)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlExistingConcertLayout.setVerticalGroup(
            pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExistingConcertLayout.createSequentialGroup()
                .addComponent(lblExistingConcert)
                .addGap(18, 18, 18)
                .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExistingConcertName)
                    .addComponent(lblExistingConcertGold)
                    .addComponent(dlblExistingConcertName)
                    .addComponent(dlblExistingConcertGold))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExistingConcertDate)
                    .addComponent(lblExistingConcertSilver)
                    .addComponent(dlblExistingConcertDate)
                    .addComponent(dlblExistingConcertSilver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExistingConcertOrganiser)
                    .addComponent(lblExistingConcertBronze)
                    .addComponent(dlblExistingConcertOrganiser)
                    .addComponent(dlblExistingConcertBronze))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pnlExistingConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditExistingConcert)
                    .addComponent(btnDeleteExistingConcert)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlNewConcert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlExistingConcert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNewConcert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlExistingConcert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewConcertGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewConcertGoldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewConcertGoldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewConcert;
    private javax.swing.JButton btnDeleteExistingConcert;
    private javax.swing.JButton btnEditExistingConcert;
    private javax.swing.JLabel dlblExistingConcertBronze;
    private javax.swing.JLabel dlblExistingConcertDate;
    private javax.swing.JLabel dlblExistingConcertGold;
    private javax.swing.JLabel dlblExistingConcertName;
    private javax.swing.JLabel dlblExistingConcertOrganiser;
    private javax.swing.JLabel dlblExistingConcertSilver;
    private javax.swing.JLabel lblAddNewConcert1;
    private javax.swing.JLabel lblExistingConcert;
    private javax.swing.JLabel lblExistingConcertBronze;
    private javax.swing.JLabel lblExistingConcertDate;
    private javax.swing.JLabel lblExistingConcertGold;
    private javax.swing.JLabel lblExistingConcertName;
    private javax.swing.JLabel lblExistingConcertOrganiser;
    private javax.swing.JLabel lblExistingConcertSilver;
    private javax.swing.JLabel lblNewConcertBronze;
    private javax.swing.JLabel lblNewConcertDate;
    private javax.swing.JLabel lblNewConcertGold;
    private javax.swing.JLabel lblNewConcertName;
    private javax.swing.JLabel lblNewConcertOrganiser;
    private javax.swing.JLabel lblNewConcertSilver;
    private javax.swing.JPanel pnlExistingConcert;
    private javax.swing.JPanel pnlNewConcert;
    private javax.swing.JTextField txtNewConcertBronze;
    private javax.swing.JTextField txtNewConcertDate;
    private javax.swing.JTextField txtNewConcertGold;
    private javax.swing.JTextField txtNewConcertName;
    private javax.swing.JTextField txtNewConcertOrganiser;
    private javax.swing.JTextField txtNewConcertSilver;
    // End of variables declaration//GEN-END:variables
}
